server.port=8081
spring.application.name=VKAcademy
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=false

#database configurations
spring.datasource.url=jdbc:mysql://localhost:3306/education_crm_db
spring.datasource.username=root
spring.datasource.password=root

#hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Razorpay Test Configuration
razorpay.key_id=rzp_test_SHh8DhmzHkvgE3
razorpay.key_secret=UtJ9PSQ51HVXAxZAoqPk22A4

# Email Configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vishalk35976@gmail.com
spring.mail.password=iyccxqxprgeeiirp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Gemini AI Configuration
gemini.api.key=AIzaSyDuohBOa6KsLSTGl35B-NLby_44MJCtlb8

# Upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
